env=Environment()

env.ParseConfig("llvm-config-3.5 --cppflags --cxxflags")
env.Append(CPPFLAGS='-Iinclude')
env.SharedLibrary('IRProfiling',['EdgeProfiling.cpp','OptimalEdgeProfiling.cpp', 'ProfileEstimatorPass.cpp', 'ProfileInfoLoader.cpp', 'ProfileInfo.cpp', 'ProfilingUtils.cpp']) 
